#spring.application.name=auth-service-flow
spring:
  application:
    name: auth-service-flow
  jpa:
    open-in-view: false

jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  access-token-ttl: 5m
  refresh-token-ttl: 1d


